Feature/lab 4
includehead/Effective_IOS_labs pull request #4
Opened 2022-11-28 05:57 UTC by includehead

2022-12-02 07:11 UTC, andrejkrasnov requested changes
пофикси коменты

2022-12-02 07:11 UTC, andrejkrasnov commented on marvel111/mainView/ListViewController.swift
> +            collectionView.reloadData()
тут не должен быть релоад 
нет загрузки а должна быть сделай еще одну ячейку
и должна быть защита что если загрузка в процессе не бьудет кидаться новый запрос

2022-12-03 19:35 UTC, includehead commented on marvel111/characterModel/CharacterModel.swift
> +    public var errorDescription: String? { return self }
убрал

2022-12-03 19:50 UTC, includehead commented on marvel111/characterModel/CharacterModel.swift
> +            for character in charactersDecodable ?? [] {
исправил на foreach

2022-12-03 19:51 UTC, includehead commented on marvel111/characterModel/CharacterModel.swift
> +                let newModel = CharacterModel(id: character?.id ?? -1, name: character?.name ?? "",
вынес

2022-12-03 19:52 UTC, includehead commented on marvel111/characterModel/CharacterModel.swift
> +            completion(.failure("Probably network error."))
прокинул

2022-12-03 19:53 UTC, includehead commented on marvel111/characterModel/CharacterModel.swift
> +            completion(.failure("Definetely network error."))
прокинул

2022-12-03 19:53 UTC, includehead commented on marvel111/characterModel/CharacterModel.swift
>                  let newModel = CharacterModel(id: character?.id ?? -1, name: character?.name ?? "",
вынес в функцию

2022-12-03 19:54 UTC, includehead commented on marvel111/fullScreenPresentation/FullScreenImageViewController.swift
> +//        wrapperView.edges(to: view)
почистил

2022-12-03 20:07 UTC, includehead commented on marvel111/fullScreenPresentation/FullScreenTransitionManager.swift
> +        button.snp.makeConstraints { make in
исправил

2022-12-03 20:12 UTC, includehead commented on marvel111/mainView/ListViewController.swift
> +    private lazy var mainScrollView: UIScrollView = { [weak self] in
исправил

2022-12-03 20:14 UTC, includehead commented on marvel111/mainView/ListViewController.swift
> +    let realm = try! Realm()
исправил на ?

2022-12-03 20:14 UTC, includehead commented on marvel111/mainView/ListViewController.swift
> +                self?.internetConnectionAvailable = false
Удалил

2022-12-03 20:24 UTC, includehead commented on marvel111/mainView/ListViewController.swift
> +            make.height.equalToSuperview()
удалил, но все равно высота и ширина нужна контенту, без этого не работает

2022-12-08 19:47 UTC, includehead commented on marvel111/mainView/ListViewController.swift
> +            collectionView.reloadData()
Исправил

2022-12-08 19:48 UTC, includehead commented on marvel111/mainView/ListViewController.swift
> +        DispatchQueue.main.async { [weak self] in
Почитал про GSC QoS, как в АФ тред поменять не понял

2022-12-15 16:52 UTC, merged