quicksave
includehead/Effective_IOS_labs pull request #5
Opened 2022-12-09 04:55 UTC by includehead

2022-12-09 05:58 UTC, andrejkrasnov requested changes

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/Network/WorkWithApi.swift
> +class WorkWithApi {
final 

всетаки это repository а не work with api

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/Network/WorkWithApi.swift
> +    private struct CharacterListDecodable: Decodable {
или payload или decodable

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/Network/WorkWithApi.swift
> +        ).responseDecodable(of: CharactersPayload.self) { response in
было бы круто если ты расширил respnseDecodable так чтобы избавиться от прокси структурки с 

SomefingPayload {
data: Полезная информация
d}

чтобы в случае кesponceDecodable вызовал получать структуруку с уже полезной информацией

внутри твой метод создавал бы что-то такое 

HttpResponce<T: Decodable> {
let data: T?
}
и возвращал httpResponce.data

тогда избавишься от одинаковых сущностей которые проксируют полезную информацию типа payload.data.value

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/Network/WorkWithApi.swift
> +        return CharacterModel(id: character?.id ?? -1, name: character?.name ?? "",
guard let payload = characte  else {
return nil
}

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/Network/WorkWithApi.swift
> +        return CharacterModel(id: character?.id ?? -1, name: character?.name ?? "",
или можено эту логику вынести в конструктор для CharacterModel

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/Network/WorkWithApi.swift
> +                var characterModelArray: [CharacterModel] = []
characterModelArray = charactersPayload.data?.results.compactMap { CharadtrMoodel(dto: $0)}

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/Network/WorkWithApi.swift
> +        return CharacterModel(id: character?.id ?? -1, name: character?.name ?? "",
extension CharacterModel {
init?(dto: CharacterPayload) {
guard let payload = dto esle {
return nil
}
init()
}
}

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/ViewModel/ViewModel.swift
> +final class ViewModel: NSObject {
Название не понятное вью моделька должна быть связнна с экраном

потом папки я бы поделил по фичам типа CharacterList  папка и там внутри CharacterListViewController и CharacterListViewModel

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/ViewModel/ViewModel.swift
> +    let realm = try? Realm()
вот это точно приятное

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/ViewModel/ViewModel.swift
> +    private lazy var charactersArray: [CharacterModel?] = [] {
вот это публичная штука и Items enum должен быть

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/ViewModel/ViewModel.swift
> +            try? realm?.write { realm?.add(newValue.compactMap { $0 }, update: .modified) }
это договаривались вынести в DataBaseManager

2022-12-09 05:58 UTC, andrejkrasnov commented on marvel111/ViewModel/ViewModel.swift
> +    private lazy var getMoreCharacters: () -> Void = {
можно функцибю пожалуйста

2022-12-11 02:15 UTC, includehead commented on marvel111/Network/WorkWithApi.swift
> +class WorkWithApi {
исправил

2022-12-11 02:15 UTC, includehead commented on marvel111/Network/WorkWithApi.swift
> +    private struct CharacterListDecodable: Decodable {
исправил

2022-12-11 02:16 UTC, includehead commented on marvel111/Network/WorkWithApi.swift
> +        ).responseDecodable(of: CharactersPayload.self) { response in
Создал функцию, принимающую generic

2022-12-11 02:20 UTC, includehead commented on marvel111/Network/WorkWithApi.swift
> +                var characterModelArray: [CharacterModel] = []
Исправил, развернув предварительно опционал

2022-12-11 04:29 UTC, includehead commented on marvel111/Network/WorkWithApi.swift
> +        return CharacterModel(id: character?.id ?? -1, name: character?.name ?? "",
исправил

2022-12-11 04:29 UTC, includehead commented on marvel111/ViewModel/ViewModel.swift
> +final class ViewModel: NSObject {
исправил

2022-12-12 02:22 UTC, includehead commented on marvel111/ViewModel/ViewModel.swift
> +            try? realm?.write { realm?.add(newValue.compactMap { $0 }, update: .modified) }
вынес

2022-12-12 02:22 UTC, includehead commented on marvel111/ViewModel/ViewModel.swift
> +    private lazy var getMoreCharacters: () -> Void = {
сделал функцию

2022-12-12 02:22 UTC, includehead commented on marvel111/ViewModel/ViewModel.swift
> +    private lazy var charactersArray: [CharacterModel?] = [] {
исправил

2022-12-14 03:59 UTC, includehead commented on marvel111/Database/DBManager.swift
> +    func getCharacter<T: Object> (id: Int) -> T? {
Переименовал

2022-12-14 04:00 UTC, includehead commented on marvel111/Database/DBManager.swift
> +extension DBManager: DatabaseProtocol {
Переименовал

2022-12-14 04:02 UTC, includehead commented on marvel111/Database/DBManager.swift
> +    func getAll() -> [CharacterModel]? {
Убрал

2022-12-14 04:05 UTC, includehead commented on marvel111/Network/Repository.swift
> +class Repository {
Добавил префикс

2022-12-14 04:12 UTC, includehead commented on marvel111/Network/Repository.swift
> +    func getCharacters(offset: Int = 0, _ completion: @escaping (Result<[CharacterModel]?, Error>) -> Void) {
исправил

2022-12-14 04:14 UTC, includehead commented on marvel111/ViewModels/FullScreenView/FullScreenImageViewController.swift
>  class FullScreenImageViewController: UIViewController {
Исправил

2022-12-14 04:55 UTC, includehead commented on marvel111/ViewModels/FullScreenView/FullScreenImageViewController.swift
> +    private let repository = Repository()
вынес

2022-12-14 05:25 UTC, includehead commented on marvel111/ViewModels/MainView/MainViewModel.swift
> +        let workItem = DispatchWorkItem { [self] in
исправил

2022-12-14 07:05 UTC, includehead commented on marvel111/ViewModels/MainView/MainViewModel.swift
> +            DispatchQueue.main.async(execute: workItem)
Убрал

2022-12-14 07:06 UTC, includehead commented on marvel111/ViewModels/MainView/MainViewModel.swift
> +    var isFetchingData = false
Переименовал

2022-12-14 07:11 UTC, includehead commented on marvel111/ViewModels/MainView/MainViewController.swift
> +        viewModel.$items.assign(to: \.items, on: self).store(in: &subscriptions)
Исправил

2022-12-14 07:48 UTC, includehead commented on marvel111/ViewModels/MainView/MainViewController.swift
> +        return items.count
исправил

2022-12-22 16:09 UTC, andrejkrasnov requested changes

2022-12-22 16:09 UTC, andrejkrasnov commented on marvel111/Database/RealmCharacterModel.swift
> +final class RealmCharacterModel: Object {
по неймингу сначала суть потом префексы Character* RealmModel, ViewCtonroller, ViewModel и тд

2022-12-22 16:09 UTC, andrejkrasnov commented on marvel111/Models/CharacterModel.swift
> +final class CharacterModel {
почему не struct ?

2022-12-22 16:09 UTC, andrejkrasnov commented on marvel111/Models/CharacterModel.swift
> +    var name: String
by default `let`

2022-12-22 16:09 UTC, andrejkrasnov commented on marvel111/Network/CharacterRepository.swift
> +class CharacterRepository {
final

2022-12-22 16:09 UTC, andrejkrasnov commented on marvel111/Network/CharacterRepository.swift
> +                completion(self.database.getAll())
если offset 0 тогда отдаем в других случаем кидаем ошибку наверх

2022-12-22 16:09 UTC, andrejkrasnov commented on marvel111/Network/CharacterRepository.swift
> +                completion(nil)
тут если у тебя в базе есть модель по айдишнику можн оее отдать если нет то кинуть ошибку

2022-12-22 16:09 UTC, andrejkrasnov commented on marvel111/ViewModels/MainView/CollectionViewLoadingIndicatorCell.swift
> +        spinner.startAnimating()
Если свернуть и развернуть приложение спинер крутиться?

2023-01-13 22:10 UTC, merged